[build]

  command = "yarn build"

  publish = "events/dist/"

[functions]

  directory = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template]
  incoming-hooks = ["dolbyio-events"]


[template.environment]
  KEY = "change me to your dolby.io app key"
  SECRET = "change me to your dolby.io app secret"
  PUBNUB_PUBLISH_KEY = "Set your pubnub publish key to enable chat"
  PUBNUB_SUBSCRIBE_KEY = "Set your pubnub subscribe key to enable chat"
  PUBNUB_SECRET_KEY = "Set your pubnub secret key to enable chat"